python:
  - "3.7.9"

jobs:
  include:
    - language: node_js
      node_js: 14
      dist: xenial
      services: sqlite3
      cache:
        - yarn: true
        - pip: true
      install:
        - cd frontend
        - yarn install
        - cd ../backend
        - pip3 install -r requirements.txt
        - cd ..
      script:
        - cd frontend
        - ./node_modules/.bin/eslint src
        - yarn test --coverage --watchAll=false
        - cd ..
        - cd backend
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
